# WEB application port
server:
  port: 7000

#spring
#application name
spring:
  application:
    name: learn-pages
#静态资源放行
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /static/**
  # datasource
#basic setttings
  datasource:
    url: jdbc:mysql://182.92.200.48:3306/mymall?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最小连接数
      minimum-idle: 1
      #最大连接数
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 30000
      connection-timeout: 3000
      connection-test-query: SELECT 1
    #management
#    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #devtools settings
  devtools:
    restart:
      enabled: true
      exclude: templates,application.yaml
  #thymeleaf settings
  thymeleaf:
    enabled: true
    mode: HTML
    cache: true
    prefix: classpath:/templates/
    encoding: UTF-8
# mybatis-plus settings
mybatis-plus:
  global-config:
    db-config:
      id-type: auto